name: OIDC

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::123456789012:role/example
          aws-region: us-east-1
      - run: echo "deploy"
